version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lab4_postgres
    environment:
      POSTGRES_DB: magasin
      POSTGRES_USER: magasin_user
      POSTGRES_PASSWORD: magasinpswd
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/local_backup.sql:/docker-entrypoint-initdb.d/local_backup.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U magasin_user -d magasin"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: lab4_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/magasin
      SPRING_DATASOURCE_USERNAME: magasin_user
      SPRING_DATASOURCE_PASSWORD: magasinpswd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    ports:
      - "8080:8080"

volumes:
  db_data: 